/**
 * European carrier programs beyond the UK, the Netherlands and Germany's DHL
 * (those are in programs.ts). Facts and sender addresses come from
 * research/worldwide/europe.md and its fact-check; where the research found no
 * confirmed sender address we list none (and say so) rather than guess, so
 * the forwarding filter never matches unrelated mail.
 */
import type { Program } from "./program";

const NO_EMAIL_ALERTS: Program["emailAlerts"] = { howToEnable: [], senders: [] };

const SHOP_SHARES_EMAIL = (carrier: string) =>
  `${carrier} emails you about a parcel when the shop passes on your email address; there's nothing to switch on.`;

const NO_CONFIRMED_SENDER = (carrier: string) =>
  `We couldn't confirm which address ${carrier}'s emails come from, so Package Radar can't add them to your forwarding filter yet. Forward them by hand if you get any.`;

export const EUROPE_PROGRAMS: Program[] = [
  {
    id: "swiss_post_my_consignments",
    name: "Swiss Post My consignments",
    operator: "Swiss Post",
    carrier: "swiss_post",
    countries: ["CH", "LI"],
    kind: "address",
    shows:
      "Swiss Post parcels and registered letters addressed to you at home appear automatically, with an alert the day before and a delivery window on the day.",
    cost: "Free",
    signupUrl: "https://meine-sendungen.post.ch/en/registration",
    dashboardUrl: "https://meine-sendungen.post.ch/en",
    verification:
      "You sign in with a SwissID (confirmed with an emailed code) and enter your home address, then Swiss Post mails a letter with a confirmation code to that address.",
    setupTime: "About 10 minutes online, then usually 1–3 days for the letter with your code",
    emailAlerts: {
      howToEnable: [
        "Sign in to My consignments with your SwissID.",
        "Open your notification settings and choose email as a channel.",
        "Save your changes.",
      ],
      senders: ["notifications@post.ch"],
    },
    parserSupport: "basic",
    gotchas: [
      "Only addresses in Switzerland and Liechtenstein qualify.",
      "If you used Swiss Post's old Customer Login, register again with a SwissID.",
      "Swiss Post warns that scammers fake its sender name, so a familiar sender alone doesn't prove an email is genuine.",
    ],
    guideSlug: null,
  },

  {
    id: "austrian_post_app",
    name: "Österreichische Post app (Post account)",
    operator: "Österreichische Post",
    carrier: "austrian_post",
    countries: ["AT"],
    kind: "address",
    shows:
      "Austrian Post parcels are added to your Post account automatically when the name and address the shop has for you match your account.",
    cost: "Free",
    signupUrl: "https://www.post.at/p/c/postapp",
    dashboardUrl: null,
    verification:
      "Registering is enough to see parcels. For delivery options such as a safe place or a Post station you identify yourself with ID Austria, a photo-ID check on your phone, or at a post office; some services send an activation code by letter.",
    setupTime: "About 5 minutes to register; identifying yourself takes a few minutes more (or a visit to a branch)",
    emailAlerts: {
      howToEnable: [
        "Sign in to your Post account in the Post app or at post.at.",
        "Turn on email notifications (e-notifications) for your parcels.",
      ],
      senders: ["meinesendung@post.at"],
    },
    parserSupport: "basic",
    gotchas: [
      "Parcels only appear when the shop's name and address for you match your Post account exactly, so some are missed.",
      "Parcels addressed to other people in your household won't appear in your account.",
      "Parcels without electronic shipping data, such as most private parcels posted at a branch, never appear.",
      "Austrian Post says it only sends email from the post.at domain.",
    ],
    guideSlug: null,
  },

  {
    id: "la_poste_mes_suivis",
    name: "La Poste Mes suivis and Colissimo emails",
    operator: "La Poste",
    carrier: "la_poste",
    countries: ["FR"],
    kind: "account",
    shows:
      "Parcels you buy on laposte.fr or at a post office while signed in, plus parcels from partner shops such as Fnac and Zalando once you turn that on, appear in your La Poste account.",
    cost: "Free",
    signupUrl: "https://aide.laposte.fr/categorie/mes-commandes-mon-espace-client/mon-espace-client/mes-suivis",
    dashboardUrl: null,
    verification: "A La Poste customer account; there's no address check.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [
        SHOP_SHARES_EMAIL("Colissimo"),
        "In your La Poste account, open Mes suivis, choose Gérer les paramètres and turn on automatic display of parcels from partner shops.",
      ],
      senders: ["noreply@notif-colissimo-laposte.info"],
    },
    parserSupport: "basic",
    gotchas: [
      "La Poste has no feature that lists every parcel coming to your address.",
      "Chronopost parcels and Prêt-à-Poster items aren't added to Mes suivis.",
      "Fake emails have also used Colissimo's sending domain, so don't pay anything through a link in an email; go to laposte.fr yourself.",
    ],
    guideSlug: null,
  },

  {
    id: "mondial_relay_emails",
    name: "Mondial Relay pickup emails",
    operator: "Mondial Relay",
    carrier: null,
    countries: ["FR", "NL"],
    kind: "per_package",
    shows:
      "Emails about one Mondial Relay parcel at a time, including when it's waiting at your pickup point or locker.",
    cost: "Free",
    signupUrl: "https://www.mondialrelay.fr/",
    dashboardUrl: null,
    verification: "None: Mondial Relay emails you when the shop (or Vinted) passes on your email address.",
    setupTime: "Nothing to set up",
    emailAlerts: {
      howToEnable: ["There's no setting to turn on: Mondial Relay emails you when the shop or Vinted passes on your email address."],
      senders: ["noreply@mondialrelay.fr", "no-reply@mondialrelay.fr", "shipping@relay.vinted.com"],
    },
    parserSupport: "basic",
    gotchas: ["Mondial Relay only emails you if the shop gave it your email address."],
    guideSlug: null,
  },

  {
    id: "correos_app",
    name: "Correos app",
    operator: "Correos",
    carrier: "correos",
    countries: ["ES"],
    kind: "account",
    shows:
      "Correos shipments that belong to you, as sender or recipient, appear automatically in the app's Actividad section, including Vinted, Wallapop and AliExpress parcels.",
    cost: "Free",
    signupUrl: "https://www.correos.es/es/es/herramientas/correos-app",
    dashboardUrl: null,
    verification: "A Correos ID account; Correos doesn't say exactly how it links shipments to you.",
    setupTime: "About 5 minutes to install the app and sign in",
    emailAlerts: NO_EMAIL_ALERTS,
    parserSupport: "basic",
    gotchas: [
      NO_CONFIRMED_SENDER("Correos"),
      "Genuine Correos parcel emails include a security code that you can check on Correos' website.",
    ],
    guideSlug: null,
  },

  {
    id: "seur_miseur",
    name: "SEUR miSEUR",
    operator: "SEUR",
    carrier: null,
    countries: ["ES"],
    kind: "account",
    shows: "SEUR shipments linked to your email address or mobile number appear in your miSEUR profile automatically.",
    cost: "Free",
    signupUrl: "https://www.seur.com/",
    dashboardUrl: null,
    verification: "A miSEUR account with your email address and mobile number.",
    setupTime: "About 5 minutes",
    emailAlerts: NO_EMAIL_ALERTS,
    parserSupport: "basic",
    gotchas: [
      "Parcels only match if the shop gave SEUR the same email address or mobile number.",
      NO_CONFIRMED_SENDER("SEUR"),
      "SEUR described this matching when miSEUR launched in 2023; the app may work differently now.",
    ],
    guideSlug: null,
  },

  {
    id: "poste_italiane_posteplus",
    name: "Poste Italiane PostePlus",
    operator: "Poste Italiane",
    carrier: "poste_italiane",
    countries: ["IT"],
    kind: "account",
    shows:
      "Poste Italiane and SDA parcels headed to you appear in one list when the shop used the same mobile number and email address you registered.",
    cost: "Free",
    signupUrl: "https://www.poste.it/posteplus",
    dashboardUrl: null,
    verification: "Your poste.it account (or PosteID/SPID), with the mobile number and email address you use for online shopping.",
    setupTime: "About 5 minutes if you already have a poste.it account",
    emailAlerts: NO_EMAIL_ALERTS,
    parserSupport: "basic",
    gotchas: [
      "Only shops that have switched the service on are covered, and they also decide whether you get emails or texts.",
      NO_CONFIRMED_SENDER("Poste Italiane"),
    ],
    guideSlug: null,
  },

  {
    id: "an_post_my_deliveries",
    name: "An Post My deliveries",
    operator: "An Post",
    carrier: "an_post",
    countries: ["IE"],
    kind: "account",
    shows:
      "Tracked An Post parcels that match the email address or phone number on your An Post account are listed automatically, including ones you're receiving.",
    cost: "Free",
    signupUrl: "https://www.anpost.com/signup",
    dashboardUrl: "https://www.anpost.com/Post-Parcels/Receiving/My-deliveries",
    verification: "An An Post account with your email address and phone number.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [
        SHOP_SHARES_EMAIL("An Post"),
        "Sign up with the email address and phone number you give shops, so parcels are listed automatically.",
      ],
      senders: ["noreply@anpost.ie"],
    },
    parserSupport: "basic",
    gotchas: [
      "Only tracked parcels appear, and only if the shop passed on your email address or phone number.",
      "If An Post leaves a parcel in a safe spot it emails you; the photo can be viewed for 7 days while you're signed in.",
      "An Post says it never sends payment links, so treat any that claim to come from An Post as a scam.",
    ],
    guideSlug: null,
  },

  {
    id: "bpost_app",
    name: "My bpost app",
    operator: "bpost",
    carrier: "bpost",
    countries: ["BE"],
    kind: "account",
    shows: "bpost parcels linked to the email addresses in your profile are added to the app automatically.",
    cost: "Free",
    signupUrl: "https://www.bpost.be/en/my-bpost-app",
    dashboardUrl: null,
    verification:
      "A bpost account with your email address(es), confirmed with a code. The account shows as validated 10 days after you create it.",
    setupTime: "About 5 minutes; the account shows as validated after 10 days",
    emailAlerts: {
      howToEnable: [SHOP_SHARES_EMAIL("bpost"), "Add every email address you shop with to your My bpost profile."],
      senders: ["noreply@communication.bpost.be"],
    },
    parserSupport: "basic",
    gotchas: [
      "Parcels from PostNL, DHL and other couriers aren't added automatically.",
      "bpost's letter preview (Mail Ahead) is still a test for selected users and doesn't cover parcels.",
    ],
    guideSlug: null,
  },

  {
    id: "inpost_mobile",
    name: "InPost Mobile",
    operator: "InPost",
    carrier: "inpost",
    countries: ["PL"],
    kind: "account",
    shows: "InPost parcels sent to your phone number appear in the app automatically, with the pickup code for Paczkomat lockers.",
    cost: "Free",
    signupUrl: "https://inpost.pl/",
    dashboardUrl: null,
    verification: "Your phone number (confirmed with a text-message code) and an email address confirmed with a link.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [
        "InPost emails you about a parcel when the shop passes on your email address.",
        "In InPost Mobile, check that email notifications are on.",
      ],
      senders: ["powiadomienia@inpost.pl", "info@paczkomaty.pl"],
    },
    parserSupport: "basic",
    gotchas: [
      "Parcels are matched by phone number, so use the number you give shops.",
      "For Allegro orders, InPost's emails come through Allegro instead (see Allegro order emails).",
      "InPost emails can include your pickup code; Package Radar doesn't store it.",
    ],
    guideSlug: null,
  },

  {
    id: "pocztex_mobile",
    name: "Pocztex Mobile (Poczta Polska)",
    operator: "Poczta Polska",
    carrier: "poczta_polska",
    countries: ["PL"],
    kind: "account",
    shows: "Poczta Polska shipments for the phone number you registered appear in the app automatically.",
    cost: "Free",
    signupUrl: "https://aplikacja.pocztex.pl/",
    dashboardUrl: null,
    verification: "An account with your phone number; you can sign in with email and password, Google, Apple, Facebook or Envelo.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [
        "Poczta Polska emails you about a shipment when the sender passes on your email address; there's nothing to switch on.",
        "Register the phone number you give shops, so shipments appear automatically.",
      ],
      senders: ["informacja@poczta-polska.pl"],
    },
    parserSupport: "basic",
    gotchas: [
      "Shipments only appear if the sender used your registered phone number.",
      "Alerts about a shipment go to whatever email address or phone number the sender gave Poczta Polska.",
    ],
    guideSlug: null,
  },

  {
    id: "moj_dhl_pl",
    name: "Mój DHL (DHL Poland)",
    operator: "DHL Parcel Poland",
    carrier: "dhl_ecommerce",
    countries: ["PL"],
    kind: "account",
    shows: "DHL parcels sent to your phone number, or to the extra phone numbers and email addresses you add, appear in the app automatically.",
    cost: "Free",
    signupUrl: "https://www.dhl.com/pl-pl/ecommerce/dla-ciebie/obsluga/kontakt/centrum-pomocy-moj-dhl.html",
    dashboardUrl: null,
    verification:
      "You register a phone number with a text-message code (it can't be changed later) and confirm any extra email addresses with a link.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [
        SHOP_SHARES_EMAIL("DHL"),
        "In Mój DHL, add every email address and phone number you shop with under Moje numery telefonu i adresy e-mail.",
      ],
      senders: ["pl.no.reply@dhl.com", "dhl.polska@dhl.pl"],
    },
    parserSupport: "basic",
    gotchas: [
      "Parcels shipped with Allegro Delivery don't appear in Mój DHL.",
      "The phone number you register first can't be changed later.",
    ],
    guideSlug: null,
  },

  {
    id: "allegro_orders",
    name: "Allegro order emails",
    operator: "Allegro",
    carrier: null,
    countries: ["PL"],
    kind: "account",
    shows:
      "Shipping updates for orders on your own Allegro account, whichever carrier delivers them, but not parcels other people send you.",
    cost: "Free with an Allegro account",
    signupUrl: "https://allegro.pl/",
    dashboardUrl: null,
    verification: "Nothing extra: these are emails Allegro already sends to the address on your account.",
    setupTime: "About 2 minutes",
    emailAlerts: {
      howToEnable: [
        "Allegro emails shipping updates to the address on your Allegro account by default.",
        "Carrier emails for Allegro orders (InPost, DPD, GLS and others) also come through Allegro, from powiadomienia@allegromail.pl.",
      ],
      senders: ["powiadomienia@allegro.pl", "powiadomienia@allegromail.pl"],
    },
    parserSupport: "basic",
    gotchas: [
      "Sellers' messages also come from powiadomienia@allegromail.pl, so they're forwarded too; Package Radar keeps only shipment details and discards the rest.",
      "Orders placed on someone else's Allegro account won't appear.",
    ],
    guideSlug: null,
  },

  {
    id: "packeta_app",
    name: "Packeta (Zásilkovna) app",
    operator: "Packeta",
    carrier: "packeta",
    countries: ["CZ"],
    kind: "account",
    shows: "Packeta parcels sent to your phone number and email address appear in the app automatically, current and past.",
    cost: "Free",
    signupUrl: "https://www.zasilkovna.cz/",
    dashboardUrl: null,
    verification: "Your phone number (confirmed with a text-message code) and your email address (confirmed with a link).",
    setupTime: "About 5 minutes",
    emailAlerts: NO_EMAIL_ALERTS,
    parserSupport: "basic",
    gotchas: [
      "A shop can give Packeta just your phone number, so not every parcel comes with an email.",
      "We couldn't confirm the exact address Packeta's Czech emails come from (they end in @zasilkovna.cz), so Package Radar can't add them to your forwarding filter yet.",
    ],
    guideSlug: null,
  },

  {
    id: "ceska_posta_online",
    name: "Česká pošta Pošta Online app",
    operator: "Česká pošta",
    carrier: null,
    countries: ["CZ"],
    kind: "account",
    shows: "Česká pošta parcels load into the app by themselves when the sender entered your phone number or email address.",
    cost: "Free",
    signupUrl: "https://www.ceskaposta.cz/en/uzitecne-nastroje/mobilni-aplikace-postaonline",
    dashboardUrl: null,
    verification: "An account in the Pošta Online app.",
    setupTime: "About 5 minutes",
    emailAlerts: NO_EMAIL_ALERTS,
    parserSupport: "basic",
    gotchas: ["The app was redesigned in 2026, so this may work differently now.", NO_CONFIRMED_SENDER("Česká pošta")],
    guideSlug: null,
  },

  {
    id: "postnord_app",
    name: "PostNord app",
    operator: "PostNord",
    carrier: "postnord",
    countries: ["SE", "DK", "NO", "FI"],
    kind: "account",
    shows: "PostNord parcels are added to the app automatically when you enter the phone number or email address you gave the shop.",
    cost: "Free",
    signupUrl: "https://www.postnord.se/en/our-tools/postnord-app/",
    signupUrlByCountry: {
      DK: "https://www.postnord.dk/en/tools/app-postnord/",
      NO: "https://www.postnord.no/en/services/postnord-app",
      FI: "https://www.postnord.fi/en/our-tools/postnord-app/",
    },
    dashboardUrl: null,
    verification: "A PostNord account with your phone number or email address; in Sweden, collecting parcels uses Mobile BankID.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [
        "In the PostNord app, add the phone number and email address you shop with.",
        "Turn on email notifications in the app's settings; otherwise PostNord mostly sends push notifications.",
      ],
      senders: ["no-reply@postnord.com", "avisering@postnord.se", "noreply@postnord.dk"],
    },
    parserSupport: "basic",
    gotchas: [
      "The email address or phone number must match the one you gave at checkout.",
      "PostNord's emails are built from the contact details the sender supplies, so a shop that only has your phone number triggers texts, not emails.",
    ],
    guideSlug: null,
  },

  {
    id: "posti_omaposti",
    name: "Posti OmaPosti",
    operator: "Posti",
    carrier: "posti",
    countries: ["FI"],
    kind: "account",
    shows: "Most deliveries headed to your phone number appear in OmaPosti automatically, with the pickup code when the number matches.",
    cost: "Free",
    signupUrl: "https://posti.fi/en/omaposti",
    dashboardUrl: null,
    verification: "Strong electronic identification (your online banking login or a mobile certificate) when you create the account, plus your phone number.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [
        "In OmaPosti, add the phone number you give shops.",
        "Check your notification settings and choose email for arrival notices.",
      ],
      senders: ["noreply@posti.fi"],
    },
    parserSupport: "basic",
    gotchas: [
      "Registered items still need ID when you collect them.",
      "We've only seen Posti's emails from noreply@posti.fi in a small sample, so some may come from another address.",
    ],
    guideSlug: null,
  },

  {
    id: "posten_bring_app",
    name: "Posten app (Posten and Bring)",
    operator: "Posten Bring",
    carrier: "posten_bring",
    countries: ["NO"],
    kind: "account",
    shows: "Posten and Bring parcels are found automatically once you register your phone number and email address in the app.",
    cost: "Free",
    signupUrl: "https://www.posten.no/en/tracking-help-page/tracking-app",
    dashboardUrl: null,
    verification: "Your phone number, activated with a code sent by text message, and your email address.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [
        "Register the phone number and email address you shop with in the Posten app.",
        "Check that email notifications are on in the app's settings.",
      ],
      senders: ["noreply@bring.com", "notification@bring.com", "no-reply@bring.com"],
    },
    parserSupport: "basic",
    gotchas: [
      "Posten mostly notifies by app and text message, so make sure email is switched on.",
      "Without the app, you can add a mobile number under your address on posten.no to get text messages instead.",
    ],
    guideSlug: null,
  },

  {
    id: "dhl_parcel_nl",
    name: "My DHL (DHL Parcel Netherlands)",
    operator: "DHL Parcel",
    carrier: "dhl_ecommerce",
    countries: ["NL"],
    kind: "account",
    shows:
      "DHL parcels sent to the email address on your My DHL account, or to up to five extra addresses you add, appear in the Received tab automatically.",
    cost: "Free",
    signupUrl: "https://www.dhlparcel.nl/en/my-dhl",
    dashboardUrl: null,
    verification: "An account with your name and email address, confirmed with a link.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [SHOP_SHARES_EMAIL("DHL"), "Add every email address you shop with to your My DHL account."],
      senders: ["noreply@dhlparcel.nl", "noreply@dhlecommerce.nl", "noreply@dhl.nl"],
    },
    parserSupport: "basic",
    gotchas: ["Parcels only appear if the shop used one of your registered email addresses."],
    guideSlug: null,
  },

  {
    id: "dpd_de",
    name: "myDPD (Germany)",
    operator: "DPD Germany",
    carrier: "dpd",
    countries: ["DE"],
    kind: "account",
    shows:
      "DPD parcels sent to the email address on your myDPD account appear automatically, with an email before delivery and a one-hour window on the day.",
    cost: "Free",
    signupUrl: "https://www.dpd.com/de/en/",
    dashboardUrl: null,
    verification:
      "A myDPD account with your email address. DPD mails a 5-digit PIN to your address only if you want to set a permanent safe place or change an address.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [SHOP_SHARES_EMAIL("DPD"), "Sign up for myDPD with the email address you shop with."],
      senders: ["noreply@service.dpd.de", "no-reply@dpd.de", "express.onlineservice@dpd.de"],
    },
    parserSupport: "basic",
    gotchas: [
      "Parcels are matched by email, so use the address you give shops.",
      "DPD's first email usually comes a day or two ahead; the one with the one-hour window comes on the delivery day.",
    ],
    guideSlug: null,
  },

  {
    id: "dpd_nl",
    name: "DPD app (Netherlands)",
    operator: "DPD Netherlands",
    carrier: "dpd",
    countries: ["NL"],
    kind: "account",
    shows:
      "DPD parcels linked to your email address appear in the DPD app automatically, with an email before delivery and a one-hour window on the day.",
    cost: "Free",
    signupUrl: "https://www.dpd.com/nl/en/",
    dashboardUrl: null,
    verification: "A DPD account with your email address.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [SHOP_SHARES_EMAIL("DPD"), "Sign up in the DPD app with the email address you shop with."],
      senders: ["noreply@dpd.nl", "noreply@dpd.com", "noreply@dpdgroup.nl"],
    },
    parserSupport: "basic",
    gotchas: [
      "Parcels are matched by email, so use the address you give shops.",
      "DPD described this automatic matching in 2022; the app may work differently now.",
    ],
    guideSlug: null,
  },

  {
    id: "dpd_baltics",
    name: "myDPD app (Estonia and Lithuania)",
    operator: "DPD Baltics",
    carrier: "dpd",
    countries: ["EE", "LT"],
    kind: "account",
    shows: "DPD parcels for the phone number and email address in your myDPD profile are added to the app automatically.",
    cost: "Free",
    signupUrl: "https://www.dpd.com/ee/en/faq/where-is-my-parcel/",
    signupUrlByCountry: { LT: "https://www.dpd.com/lt/en/faq/is-an-email-address-mandatory" },
    dashboardUrl: null,
    verification: "A myDPD profile with your phone number and email address.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [SHOP_SHARES_EMAIL("DPD"), "Add the phone number and email address you shop with to your myDPD profile."],
      senders: ["noreply@dpdbaltics.com"],
    },
    parserSupport: "basic",
    gotchas: ["Parcels only appear if the shop gave DPD the same phone number or email address."],
    guideSlug: null,
  },

  {
    id: "dpd_be",
    name: "myDPD consignee profile (Belgium)",
    operator: "DPD Belgium",
    carrier: "dpd",
    countries: ["BE"],
    kind: "account",
    shows:
      "DPD parcels appear in your myDPD profile automatically when the shop gave DPD the email address or phone number in your profile and the parcel's postcode matches yours.",
    cost: "Free",
    signupUrl: "https://www.dpd.com/be/en/",
    dashboardUrl: null,
    verification: "A myDPD profile with your email address, phone number and postcode.",
    setupTime: "About 5 minutes",
    emailAlerts: NO_EMAIL_ALERTS,
    parserSupport: "basic",
    gotchas: [
      "A parcel only matches when both your postcode and the email address or phone number the shop gave DPD match your profile.",
      NO_CONFIRMED_SENDER("DPD Belgium"),
    ],
    guideSlug: null,
  },

  {
    id: "gls_app",
    name: "GLS app and account",
    operator: "GLS",
    carrier: "gls",
    countries: ["DE", "AT"],
    kind: "account",
    shows: "GLS parcels are added to your account automatically when the shop put one of your registered email addresses on the delivery data.",
    cost: "Free",
    signupUrl: "https://gls-group.com/",
    signupUrlByCountry: { AT: "https://gls-group.com/AT/de/faq/gls-one/" },
    dashboardUrl: null,
    verification: "A GLS account with the email addresses you shop with.",
    setupTime: "About 5 minutes",
    emailAlerts: {
      howToEnable: [SHOP_SHARES_EMAIL("GLS"), "Add every email address you shop with to your GLS account."],
      senders: ["noreply@gls-group.eu", "no-reply@gls-pakete.de"],
      sendersByCountry: { AT: ["noreply@gls-group.eu", "noreply@gls-rtt.com"] },
    },
    parserSupport: "basic",
    gotchas: [
      "GLS's delivery emails give a time window of a few hours.",
      "You can set a permanent safe place, but not a permanent redirect.",
    ],
    guideSlug: null,
  },

  {
    id: "hermes_de_emails",
    name: "Hermes parcel emails",
    operator: "Hermes Germany",
    carrier: "hermes",
    countries: ["DE"],
    kind: "per_package",
    shows:
      "Emails about one Hermes parcel at a time when the shop passes on your email address; we know of no Hermes feature that lists every parcel coming to you.",
    cost: "Free",
    signupUrl: "https://www.myhermes.de/",
    dashboardUrl: null,
    verification: "None: Hermes emails you when the shop shares your email address.",
    setupTime: "Nothing to set up",
    emailAlerts: {
      howToEnable: ["There's no setting to turn on: Hermes emails you about a parcel when the shop passes on your email address."],
      senders: ["noreply@paketankuendigung.myhermes.de", "info-paket@myhermes.de"],
    },
    parserSupport: "basic",
    gotchas: [
      "Hermes only emails you if the shop gave Hermes your email address.",
      "With a myhermes.de account you can set a permanent redirect to a ParcelShop.",
    ],
    guideSlug: null,
  },

  {
    id: "ctt_app",
    name: "CTT app",
    operator: "CTT",
    carrier: "ctt",
    countries: ["PT"],
    kind: "account",
    shows: "Parcels from shops that work with CTT are added to your CTT account automatically; you can add others by tracking number.",
    cost: "Free",
    signupUrl: "https://www.ctt.pt/",
    dashboardUrl: null,
    verification: "A free CTT account.",
    setupTime: "About 5 minutes",
    emailAlerts: NO_EMAIL_ALERTS,
    parserSupport: "basic",
    gotchas: ["Only shops that work with CTT add parcels automatically.", NO_CONFIRMED_SENDER("CTT")],
    guideSlug: null,
  },

  {
    id: "omniva_self_service",
    name: "Omniva self-service",
    operator: "Omniva",
    carrier: null,
    countries: ["EE", "LV", "LT"],
    kind: "account",
    shows: "Omniva's self-service lists shipments coming to you that are linked to you through the shipment's details.",
    cost: "Free",
    signupUrl: "https://minu.omniva.ee/",
    dashboardUrl: null,
    verification: "You sign in with Smart-ID, Mobile-ID or an ID card.",
    setupTime: "About 5 minutes",
    emailAlerts: NO_EMAIL_ALERTS,
    parserSupport: "basic",
    gotchas: [
      "Omniva can alert you by text message, push notification or email, but we couldn't confirm which address its emails come from, so Package Radar can't add them to your forwarding filter yet.",
      "We couldn't confirm exactly how Omniva links shipments to you.",
    ],
    guideSlug: null,
  },

  {
    id: "sameday_app",
    name: "Sameday app",
    operator: "Sameday",
    carrier: null,
    countries: ["RO"],
    kind: "account",
    shows: "Deliveries for your phone number from the last 90 days appear in the app, including easybox locker deliveries.",
    cost: "Free",
    signupUrl: "https://sameday.ro/",
    dashboardUrl: null,
    verification: "Your phone number, or an eMAG, Apple or Google login.",
    setupTime: "About 5 minutes",
    emailAlerts: NO_EMAIL_ALERTS,
    parserSupport: "basic",
    gotchas: ["Sameday notifies you in the app and by text message; we couldn't find email alerts we could forward."],
    guideSlug: null,
  },
];
